#高可用2个节点
#应用名称及验证账号
spring:
  application:
    name: eureka
#  security:
#    user:
#      name: root
#      password: root
logging:
  level:
    root: debug
server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901
    prefer-ip-address: false
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/,http://eureka-7903:7903/eureka/
    register-with-eureka: true
    fetch-registry: true
#  server:
#    enable-self-preservation: false